# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_recentaddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentaddresses',
            name='imageFile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
