# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_pagecounter_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecounter',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
